use crate::schema::Registry;

pub fn generated_rust(registry: &Registry) -> String {
    let mut out =
        String::from("// @generated by old-church-slavonic-extractor. Do not edit manually.\n");
    out.push_str("pub(crate) static LEXEMES: &[LexemeRecord] = &[\n");
    for row in &registry.lexemes {
        out.push_str(&format!(
            "    LexemeRecord {{ id: {:?}, lemma: {:?}, key: {:?}, pos: {:?}, class: {:?}, gender: {:?}, animacy: {:?}, number_restriction: {:?} }},\n",
            row.id,
            row.lemma,
            row.key,
            row.pos,
            row.class,
            row.gender,
            row.animacy,
            row.number_restriction
        ));
    }
    out.push_str("];\n");
    out.push_str("pub(crate) static ALIASES: &[AliasRecord] = &[\n");
    for row in &registry.aliases {
        out.push_str(&format!(
            "    AliasRecord {{ key: {:?}, lexeme_id: {:?} }},\n",
            row.key, row.lexeme_id
        ));
    }
    out.push_str("];\n");
    out.push_str("pub(crate) static FORMS: &[FormRecord] = &[\n");
    for row in &registry.forms {
        out.push_str(&format!(
            "    FormRecord {{ lexeme_id: {:?}, feature: {:?}, rank: {}, form: {:?}, romanization: {:?} }},\n",
            row.lexeme_id,
            row.feature,
            row.rank,
            row.form,
            row.romanization,
        ));
    }
    out.push_str("];\n");
    out.push_str("pub(crate) static OVERRIDES: &[OverrideRecord] = &[\n");
    for row in &registry.overrides {
        out.push_str(&format!(
            "    OverrideRecord {{ lexeme_id: {:?}, feature: {:?}, rank: {}, form: {:?}, romanization: {:?}, reason: {:?}, authority: {:?} }},\n",
            row.lexeme_id,
            row.feature,
            row.rank,
            row.form,
            row.romanization,
            row.reason,
            row.authority,
        ));
    }
    out.push_str("];\n");
    out.push_str("pub(crate) static VERB_METADATA: &[VerbMetadataRecord] = &[\n");
    for row in &registry.verb_metadata {
        out.push_str(&format!(
            "    VerbMetadataRecord {{ lexeme_id: {:?}, system: {:?}, analysis_rank: {}, field: {:?}, value: {:?}, provenance: {:?}, source_feature: {:?}, source_form: {:?}, crosscheck_features: {:?}, authority: {:?} }},\n",
            row.lexeme_id,
            row.system,
            row.analysis_rank,
            row.field,
            row.value,
            row.provenance,
            row.source_feature,
            row.source_form,
            row.crosscheck_features,
            row.authority,
        ));
    }
    out.push_str("];\n");
    out
}
