use crate::schema::Registry;

pub fn generated_rust(registry: &Registry) -> String {
    let mut out =
        String::from("// @generated by old-church-slavonic-extractor. Do not edit manually.\n");
    out.push_str("pub(crate) static LEXEMES: &[LexemeRecord] = &[\n");
    for row in &registry.lexemes {
        out.push_str(&format!(
            "    LexemeRecord {{ id: {:?}, lemma: {:?}, key: {:?}, pos: {:?}, class: {:?}, gender: {:?}, animacy: {:?}, number_restriction: {:?} }},\n",
            row.id,
            row.lemma,
            row.key,
            row.pos,
            row.class,
            row.gender,
            row.animacy,
            row.number_restriction
        ));
    }
    out.push_str("];\n");
    out.push_str("pub(crate) static ALIASES: &[AliasRecord] = &[\n");
    for row in &registry.aliases {
        out.push_str(&format!(
            "    AliasRecord {{ key: {:?}, lexeme_id: {:?} }},\n",
            row.key, row.lexeme_id
        ));
    }
    out.push_str("];\n");
    out.push_str("pub(crate) static FORMS: &[FormRecord] = &[\n");
    for row in &registry.forms {
        out.push_str(&format!(
            "    FormRecord {{ lexeme_id: {:?}, feature: {:?}, rank: {}, form: {:?}, romanization: {:?}, is_override: {} }},\n",
            row.lexeme_id,
            row.feature,
            row.rank,
            row.form,
            row.romanization,
            row.source_tags == "manual-override"
        ));
    }
    out.push_str("];\n");
    out
}
