[package]
name = "extractor-legacy"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[features]
default = []
checks = ["dep:church-slavonic-legacy"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
unicode-normalization = { workspace = true }
church-slavonic-core-legacy = { path = "../church-slavonic-core" }
church-slavonic-legacy = { path = "../church-slavonic", optional = true }

[lints]
workspace = true
