//! Dictionary slice of the rewrite pilot: generate the sorted-slice sense
//! tables consumed by the `church-slavonic-dictionary` crate, and gate their
//! consistency against the `church-slavonic` facade.
//!
//! - `cargo xtask rewrite-dictionary` rewrites
//!   `crates/church-slavonic-dictionary/generated/entries.rs` from
//!   `data/dictionary/senses.json` (the same pinned Kaikki/Wiktionary
//!   extraction the old `old-church-slavonic-dictionary` table came from).
//! - `rewrite_dictionary::check` (wired into `cargo xtask check-structure`)
//!   regenerates the table text and demands it match the committed file,
//!   verifies every pinned sense lemma key resolves through the facade's
//!   paradigm enumeration, and replays the full lemmatize round-trip: for
//!   every enumerated paradigm surface, `lemmatize(surface)` must contain
//!   the generating (lemma key, cell) reading.
//!
//! Homograph mapping rule: a sense's `inflection_lexeme_id` names one
//! extracted lexeme; `rewrite_pilot::dictionary_support` replays the residue
//! emitters' own deterministic homograph sort (form inventory, then encoded
//! metadata, then lexeme id) to assign that lexeme the identical bare or
//! `_2`/`_3` suffixed key the facade serves it under. Senses with no lexeme
//! id keep `lemma_key: None`.

use crate::rewrite_pilot;
use serde::Deserialize;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;
use std::time::Instant;

#[derive(Debug, Deserialize)]
struct SourceSense {
    id: String,
    source_sense_id: String,
    lemma: String,
    page_word: String,
    key: String,
    page_key: String,
    part_of_speech: String,
    inflection_lexeme_id: Option<String>,
    glosses: Vec<String>,
    raw_glosses: Vec<String>,
    tags: Vec<String>,
    topics: Vec<String>,
}

fn string_slice(out: &mut String, values: &[String]) {
    out.push_str("&[");
    for (index, value) in values.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        let _ = write!(out, "{value:?}");
    }
    out.push(']');
}

/// Render the generated table text from the pinned sense source and the
/// pilot's lemma-key inventory. Deterministic: sorted slices only.
fn render(root: &Path) -> Result<(String, RenderStats), Box<dyn Error>> {
    let support = rewrite_pilot::dictionary_support(root)?;
    let mut senses: Vec<SourceSense> =
        serde_json::from_slice(&fs::read(root.join("data/dictionary/senses.json"))?)?;
    senses.sort_by(|left, right| (&left.key, &left.id).cmp(&(&right.key, &right.id)));
    let mut pinned = 0usize;
    let mut unmapped: Vec<&str> = Vec::new();
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo xtask rewrite-dictionary`. Do not edit.\n\
         //\n\
         // SENSES: one row per Wiktionary sense from data/dictionary/senses.json,\n\
         // sorted by (lookup key, id). `lemma_key` is the `church-slavonic` facade\n\
         // lemma key (deterministic numeric homograph suffix included) for senses\n\
         // the source pins to an extracted lexeme. PAGE_INDEX maps accentless page\n\
         // keys to sense indices; LEMMA_KEY_INDEX maps facade lemma keys to sense\n\
         // indices; LEMMAS is the facade lemma-key inventory with part-of-speech\n\
         // codes (1 noun, 2 adjective, 3 verb, 4 pronoun, 5 numeral,\n\
         // 6 determiner). All slices are sorted for binary search.\n",
    );
    let _ = writeln!(
        out,
        "pub(crate) static SENSES: &[SenseRecord] = &[ // {} senses",
        senses.len()
    );
    for sense in &senses {
        let lemma_key = match &sense.inflection_lexeme_id {
            Some(id) => match support.key_by_lexeme.get(id) {
                Some(key) => {
                    pinned += 1;
                    Some(key.as_str())
                }
                None => {
                    unmapped.push(id);
                    None
                }
            },
            None => None,
        };
        let _ = write!(
            out,
            "    SenseRecord {{ id: {:?}, source_sense_id: {:?}, lemma: {:?}, \
             page_word: {:?}, key: {:?}, page_key: {:?}, part_of_speech: {:?}, lemma_key: ",
            sense.id,
            sense.source_sense_id,
            sense.lemma,
            sense.page_word,
            sense.key,
            sense.page_key,
            sense.part_of_speech,
        );
        match lemma_key {
            Some(key) => {
                let _ = write!(out, "Some({key:?})");
            }
            None => out.push_str("None"),
        }
        out.push_str(", glosses: ");
        string_slice(&mut out, &sense.glosses);
        out.push_str(", raw_glosses: ");
        string_slice(&mut out, &sense.raw_glosses);
        out.push_str(", tags: ");
        string_slice(&mut out, &sense.tags);
        out.push_str(", topics: ");
        string_slice(&mut out, &sense.topics);
        out.push_str(" },\n");
    }
    out.push_str("];\n");

    // Page-key index: only rows whose page key differs from the primary key
    // (the primary key is served by the sorted SENSES slice itself).
    let mut page_index: Vec<(&str, usize)> = senses
        .iter()
        .enumerate()
        .filter(|(_, sense)| sense.page_key != sense.key)
        .map(|(index, sense)| (sense.page_key.as_str(), index))
        .collect();
    page_index.sort();
    let _ = writeln!(
        out,
        "pub(crate) static PAGE_INDEX: &[(&str, u32)] = &[ // {} rows",
        page_index.len()
    );
    for (page_key, index) in &page_index {
        let _ = writeln!(out, "    ({page_key:?}, {index}),");
    }
    out.push_str("];\n");

    let mut lemma_key_index: Vec<(&str, usize)> = Vec::new();
    for (index, sense) in senses.iter().enumerate() {
        if let Some(id) = &sense.inflection_lexeme_id {
            if let Some(key) = support.key_by_lexeme.get(id) {
                lemma_key_index.push((key.as_str(), index));
            }
        }
    }
    lemma_key_index.sort();
    let _ = writeln!(
        out,
        "pub(crate) static LEMMA_KEY_INDEX: &[(&str, u32)] = &[ // {} rows",
        lemma_key_index.len()
    );
    for (key, index) in &lemma_key_index {
        let _ = writeln!(out, "    ({key:?}, {index}),");
    }
    out.push_str("];\n");

    let _ = writeln!(
        out,
        "pub(crate) static LEMMAS: &[(&str, u8)] = &[ // {} lemma keys",
        support.lemma_pos.len()
    );
    for (lemma, pos) in &support.lemma_pos {
        let _ = writeln!(out, "    ({lemma:?}, {pos}),");
    }
    out.push_str("];\n");

    unmapped.sort();
    unmapped.dedup();
    if !unmapped.is_empty() {
        return Err(format!(
            "{} sense lexeme ids missing from the pilot inventory: {:?}",
            unmapped.len(),
            &unmapped[..unmapped.len().min(10)]
        )
        .into());
    }
    Ok((
        out,
        RenderStats {
            senses: senses.len(),
            pinned,
            lemmas: support.lemma_pos.len(),
        },
    ))
}

struct RenderStats {
    senses: usize,
    pinned: usize,
    lemmas: usize,
}

fn generated_path(root: &Path) -> std::path::PathBuf {
    root.join("crates/church-slavonic-dictionary/generated/entries.rs")
}

/// `cargo xtask rewrite-dictionary`: rewrite the generated table.
pub(crate) fn emit(root: &Path) -> Result<(), Box<dyn Error>> {
    let (out, stats) = render(root)?;
    let path = generated_path(root);
    fs::write(&path, &out)?;
    println!(
        "wrote {} ({} bytes): {} senses ({} pinned to facade lemma keys), {} lemma keys",
        path.display(),
        out.len(),
        stats.senses,
        stats.pinned,
        stats.lemmas,
    );
    Ok(())
}

/// Dictionary consistency gate (see the module docs). Prints its numbers.
pub(crate) fn check(root: &Path) -> Result<(), Box<dyn Error>> {
    let (expected, stats) = render(root)?;
    if fs::read_to_string(generated_path(root))? != expected {
        return Err("committed church-slavonic-dictionary tables are stale; \
             run cargo xtask rewrite-dictionary"
            .into());
    }

    // 1. Every pinned sense lemma key resolves through the facade.
    let mut resolved = 0usize;
    for sense in church_slavonic_dictionary::senses() {
        let Some(key) = sense.lemma_key() else {
            continue;
        };
        let known = church_slavonic::noun_paradigm(key).is_ok()
            || church_slavonic::verb_paradigm(key).is_ok()
            || church_slavonic::adjective_paradigm(key, church_slavonic::AdjectiveForm::Long)
                .is_ok()
            || church_slavonic::pronoun_form_paradigm(key).is_ok()
            || church_slavonic::numeral_form_paradigm(key).is_ok()
            || church_slavonic::determiner_form_paradigm(key).is_ok();
        if !known {
            return Err(format!(
                "dictionary sense {} pins lemma key {key} that no facade paradigm serves",
                sense.id()
            )
            .into());
        }
        resolved += 1;
    }

    // 2. Full lemmatize round-trip over every enumerated paradigm surface.
    use church_slavonic_dictionary::{Cell, Pos, Reading, lemmatize};
    let started = Instant::now();
    let mut surfaces = 0usize;
    let mut failures: Vec<String> = Vec::new();
    let mut require = |lemma: &'static str, pos: Pos, cell: Cell, surface: &str| {
        surfaces += 1;
        if !lemmatize(surface).contains(&Reading { lemma, pos, cell }) && failures.len() < 10 {
            failures.push(format!("{surface} !-> {lemma} {cell:?}"));
        }
    };
    for (lemma, pos) in church_slavonic_dictionary::lemmas() {
        match pos {
            Pos::Noun => {
                if let Ok(paradigm) = church_slavonic::noun_paradigm(lemma) {
                    for (case, number, variants) in paradigm {
                        for surface in &variants {
                            require(lemma, pos, Cell::Noun { case, number }, surface);
                        }
                    }
                }
            }
            Pos::Adjective => {
                for form in [
                    church_slavonic::AdjectiveForm::Long,
                    church_slavonic::AdjectiveForm::Short,
                ] {
                    if let Ok(paradigm) = church_slavonic::adjective_paradigm(lemma, form) {
                        for (case, number, gender, variants) in paradigm {
                            for surface in &variants {
                                require(
                                    lemma,
                                    pos,
                                    Cell::Adjective {
                                        form,
                                        case,
                                        number,
                                        gender,
                                    },
                                    surface,
                                );
                            }
                        }
                    }
                }
            }
            Pos::Verb => {
                if let Ok(paradigm) = church_slavonic::verb_paradigm(lemma) {
                    for (kind, variants) in paradigm {
                        for surface in &variants {
                            require(lemma, pos, Cell::Verb(kind), surface);
                        }
                    }
                }
            }
            Pos::Pronoun | Pos::Numeral | Pos::Determiner => {
                let paradigm = match pos {
                    Pos::Pronoun => church_slavonic::pronoun_form_paradigm(lemma),
                    Pos::Numeral => church_slavonic::numeral_form_paradigm(lemma),
                    _ => church_slavonic::determiner_form_paradigm(lemma),
                };
                if let Ok(paradigm) = paradigm {
                    for (case, number, gender, variants) in paradigm {
                        for surface in &variants {
                            require(
                                lemma,
                                pos,
                                Cell::Closed {
                                    case,
                                    number,
                                    gender,
                                },
                                surface,
                            );
                        }
                    }
                }
            }
        }
    }
    if !failures.is_empty() {
        return Err(format!("lemmatize round-trip failures: {failures:?}").into());
    }
    println!(
        "dictionary consistency: {} senses ({} pinned lemma keys, all resolving), \
         {} lemma keys, lemmatize round-trip {surfaces}/{surfaces} surfaces \
         ({} ms including index build)",
        stats.senses,
        resolved,
        stats.lemmas,
        started.elapsed().as_millis(),
    );
    Ok(())
}
