//! The shared lexeme-identity layer (docs/UNIFIED_IDENTITY.md).
//!
//! One lemma space across recensions: each entry keys an abstract lexeme by
//! its projection-normal identity key and attaches the per-recension citation
//! surfaces plus the two families' native IDs. The kernel owns only the type
//! and the resolution logic; the committed table lives in
//! `data/unified/identity.tsv` (generated by `cargo xtask unified-identity`)
//! and is passed in as text by the consumer — this crate ships no data.
//!
//! The abstract key is a keying convention, not a reconstructed form: the
//! accentless-folded projection-normal form both citation surfaces reduce to,
//! prefixed with the shared part-of-speech code and suffixed with a
//! deterministic numeric homograph discriminator assigned once per abstract
//! lexeme (never re-sorted per recension). See docs/UNIFIED_IDENTITY.md.

use std::collections::BTreeMap;
use std::fmt;

/// One abstract lexeme: the identity key and its per-recension attachments.
#[derive(Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
pub struct IdentityEntry {
    /// The abstract identity key, e.g. `noun:агнецъ` or `noun:агнецъ_2`.
    pub abstract_key: String,
    /// Shared part-of-speech code (`noun`, `adj`, `verb`, `pron`, `num`, `det`).
    pub pos: String,
    /// Native ID of the OCS lexeme in the extracted registry
    /// (`data/extracted/lexemes.tsv`, e.g. `агньць|noun|2c37c8984ac3639b`).
    pub ocs_lexeme_id: String,
    /// OCS citation surface (the Wiktionary lemma, accents as printed).
    pub ocs_citation: String,
    /// The `church-slavonic` facade lemma key serving this lexeme
    /// (deterministic homograph suffix included), when the facade serves it.
    pub ocs_lemma_key: Option<String>,
    /// Native ID of the Synodal lexeme (`data/synodal/lexemes.tsv`,
    /// e.g. `synodal:noun:agnets`) — usable with the Synodal `Inflector`.
    pub synodal_lexeme_id: String,
    /// Synodal citation surface (the registered lemma).
    pub synodal_citation: String,
}

/// Error parsing an identity table.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct IdentityParseError {
    /// 1-based line number in the input text.
    pub line: usize,
    /// What was wrong with the line.
    pub message: String,
}

impl fmt::Display for IdentityParseError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "identity table line {}: {}",
            self.line, self.message
        )
    }
}

impl std::error::Error for IdentityParseError {}

/// The shared identity registry: abstract key -> per-recension surfaces and
/// native IDs, with reverse lookups from either family's native ID.
///
/// Minimal honest phase-2 view layer: it does not rewrite either family's
/// internals — it resolves between them. The OCS lemma key plugs into the
/// `church-slavonic` facade functions; the Synodal lexeme ID plugs into the
/// `synodal-church-slavonic` `Inflector` (`form_by_id`).
#[derive(Clone, Debug, Default)]
pub struct IdentityRegistry {
    entries: Vec<IdentityEntry>,
    by_key: BTreeMap<String, usize>,
    by_ocs_id: BTreeMap<String, usize>,
    by_synodal_id: BTreeMap<String, usize>,
}

impl IdentityRegistry {
    /// Number of columns in `identity.tsv` body rows.
    pub const COLUMNS: usize = 7;

    /// Parses the committed `data/unified/identity.tsv` text. `#` comment
    /// lines are skipped; the first non-comment line is the column header.
    /// Duplicate abstract keys or native IDs are errors — the identity
    /// stability rule demands one entry per abstract lexeme.
    pub fn parse(text: &str) -> Result<Self, IdentityParseError> {
        let mut registry = Self::default();
        let mut header_seen = false;
        for (index, line) in text.lines().enumerate() {
            let number = index + 1;
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            if !header_seen {
                header_seen = true;
                continue;
            }
            let fields: Vec<&str> = line.split('\t').collect();
            if fields.len() != Self::COLUMNS {
                return Err(IdentityParseError {
                    line: number,
                    message: format!("expected {} columns, found {}", Self::COLUMNS, fields.len()),
                });
            }
            let entry = IdentityEntry {
                abstract_key: fields[0].to_owned(),
                pos: fields[1].to_owned(),
                ocs_lexeme_id: fields[2].to_owned(),
                ocs_citation: fields[3].to_owned(),
                ocs_lemma_key: (!fields[4].is_empty()).then(|| fields[4].to_owned()),
                synodal_lexeme_id: fields[5].to_owned(),
                synodal_citation: fields[6].to_owned(),
            };
            registry
                .insert(entry)
                .map_err(|message| IdentityParseError {
                    line: number,
                    message,
                })?;
        }
        Ok(registry)
    }

    fn insert(&mut self, entry: IdentityEntry) -> Result<(), String> {
        let index = self.entries.len();
        if self
            .by_key
            .insert(entry.abstract_key.clone(), index)
            .is_some()
        {
            return Err(format!("duplicate abstract key {}", entry.abstract_key));
        }
        if self
            .by_ocs_id
            .insert(entry.ocs_lexeme_id.clone(), index)
            .is_some()
        {
            return Err(format!("duplicate OCS lexeme id {}", entry.ocs_lexeme_id));
        }
        if self
            .by_synodal_id
            .insert(entry.synodal_lexeme_id.clone(), index)
            .is_some()
        {
            return Err(format!(
                "duplicate Synodal lexeme id {}",
                entry.synodal_lexeme_id
            ));
        }
        self.entries.push(entry);
        Ok(())
    }

    /// All entries, in table order (sorted by abstract key by construction).
    #[must_use]
    pub fn entries(&self) -> &[IdentityEntry] {
        &self.entries
    }

    /// Number of abstract lexemes in the registry.
    #[must_use]
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Whether the registry is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Resolves an abstract key to its full entry.
    #[must_use]
    pub fn resolve(&self, abstract_key: &str) -> Option<&IdentityEntry> {
        self.by_key
            .get(abstract_key)
            .map(|&index| &self.entries[index])
    }

    /// Resolves an abstract key to the OCS facade lemma key — the string the
    /// `church-slavonic` facade's paradigm functions accept (homograph
    /// suffix included). `None` when the key is unknown or the facade does
    /// not serve this lexeme.
    #[must_use]
    pub fn ocs_lemma_key(&self, abstract_key: &str) -> Option<&str> {
        self.resolve(abstract_key)?.ocs_lemma_key.as_deref()
    }

    /// Resolves an abstract key to the Synodal native lexeme ID — the string
    /// to wrap in `LexemeId` for the Synodal `Inflector`.
    #[must_use]
    pub fn synodal_lexeme_id(&self, abstract_key: &str) -> Option<&str> {
        self.resolve(abstract_key)
            .map(|entry| entry.synodal_lexeme_id.as_str())
    }

    /// Reverse lookup: the entry owning a native OCS extracted-lexeme ID.
    #[must_use]
    pub fn by_ocs_lexeme_id(&self, ocs_lexeme_id: &str) -> Option<&IdentityEntry> {
        self.by_ocs_id
            .get(ocs_lexeme_id)
            .map(|&index| &self.entries[index])
    }

    /// Reverse lookup: the entry owning a native Synodal lexeme ID.
    #[must_use]
    pub fn by_synodal_lexeme_id(&self, synodal_lexeme_id: &str) -> Option<&IdentityEntry> {
        self.by_synodal_id
            .get(synodal_lexeme_id)
            .map(|&index| &self.entries[index])
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "# identity.tsv sample\n\
        abstract_key\tpos\tocs_lexeme_id\tocs_citation\tocs_lemma_key\tsynodal_lexeme_id\tsynodal_citation\n\
        noun:агнецъ\tnoun\tагньць|noun|2c37c8984ac3639b\tагньць\tагньць\tsynodal:noun:agnets\tагнецъ\n\
        verb:быти\tverb\tбꙑти|verb|deadbeef00000000\tбꙑти\t\tsynodal:verb:byti\tбыти\n";

    #[test]
    fn parses_and_resolves_both_directions() {
        let registry = IdentityRegistry::parse(SAMPLE).expect("parses");
        assert_eq!(registry.len(), 2);
        let entry = registry.resolve("noun:агнецъ").expect("resolves");
        assert_eq!(entry.synodal_citation, "агнецъ");
        assert_eq!(registry.ocs_lemma_key("noun:агнецъ"), Some("агньць"));
        assert_eq!(registry.ocs_lemma_key("verb:быти"), None);
        assert_eq!(
            registry.synodal_lexeme_id("verb:быти"),
            Some("synodal:verb:byti")
        );
        assert_eq!(
            registry
                .by_ocs_lexeme_id("агньць|noun|2c37c8984ac3639b")
                .map(|entry| entry.abstract_key.as_str()),
            Some("noun:агнецъ")
        );
        assert_eq!(
            registry
                .by_synodal_lexeme_id("synodal:verb:byti")
                .map(|entry| entry.abstract_key.as_str()),
            Some("verb:быти")
        );
        assert!(registry.resolve("noun:никакой").is_none());
    }

    #[test]
    fn rejects_duplicate_abstract_keys() {
        let text = "header\nk\tnoun\ta\tb\tc\td\te\nk\tnoun\tf\tg\th\ti\tj\n";
        let error = IdentityRegistry::parse(text).expect_err("duplicate rejected");
        assert!(error.message.contains("duplicate abstract key"));
    }

    #[test]
    fn rejects_wrong_column_count() {
        let text = "header\nonly\tthree\tcolumns\n";
        assert!(IdentityRegistry::parse(text).is_err());
    }
}
