//! Stable rule identifiers and optional rule traces.

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RuleId {
    NounOMasculineHard,
    NounONeuterHard,
    NounJoMasculineSoft,
    NounJoNeuterSoft,
    NounAHard,
    NounJaSoft,
    NounIFeminine,
    NounIMasculine,
    NounUMasculine,
    NounNMasculine,
    NounNNeuter,
    NounNtNeuter,
    NounRStem,
    NounSNeuter,
    NounVFeminine,
    NounIndeclinable,
    AdjectiveHardShort,
    AdjectiveHardLong,
    AdjectiveSoftShort,
    AdjectiveSoftLong,
    AdjectiveComparativeNew,
    AdjectiveComparativeOld,
    AdjectiveSuperlativePre,
    PhraseRelativeSuperlative,
    PhraseAbsoluteSuperlativeAdverb,
    PhraseDaImperative,
    PhrasePerfect,
    PhrasePluperfect,
    PhraseFutureInfinitive,
    PhraseFutureParticiple,
    PhraseFuturePerfect,
    PhraseConditionalOptative,
    PhraseConditionalOptativeDa,
    PhraseConditionalOptativeElliptical,
    PhraseConditionalOptativePassive,
    PhraseAnalyticPassive,
    PronounPersonalFirst,
    PronounPersonalSecond,
    PronounReflexive,
    PronounPersonalClitic,
    PronounAnaphoricThird,
    PronounAnaphoricPrepositional,
    PronounPronominalHard,
    PronounPronominalSoft,
    PronounPronominalJ,
    PronounPronominalVelar,
    PronounRelativeIzhe,
    PronounRelativePrepositional,
    PronounSpecialVes,
    PronounSpecialSic,
    PronounUniqueSi,
    PronounInterrogativeKto,
    PronounInterrogativeChto,
    DeterminerInterrogativeKyi,
    VerbCopulaPresentEs,
    VerbCopulaFutureBud,
    VerbCopulaImperfectBe,
    VerbCopulaAoristBe,
    VerbCopulaConditionalBi,
    VerbCopulaConditionalAoristBy,
    VerbIA1,
    VerbIA2,
    VerbII1,
    VerbII2,
    VerbII3,
    VerbDictionaryMetadata,
    VerbInfinitive,
    VerbSupine,
    VerbLParticiple,
    VerbImperfectA,
    VerbImperfectYatA,
    VerbImperfectPalatalizedA,
    VerbImperfectContractedA,
    VerbImperfectContractedYatA,
    VerbImperfectContractedPalatalizedA,
    VerbImperfectPresent,
    VerbImperfectPresentContracted,
    VerbImperfectIotated,
    VerbAoristAsigmatic,
    VerbAoristSigmaticPrimary,
    VerbAoristSigmaticSecondary,
    VerbAoristSigmaticVowel,
    VerbAoristNew,
    VerbImperative,
    VerbParticiplePresentActive,
    VerbParticiplePresentPassive,
    VerbParticiplePastActive,
    VerbParticiplePastPassive,
}

impl RuleId {
    pub const fn code(self) -> &'static str {
        match self {
            Self::NounOMasculineHard => "N-O-M-HARD-01",
            Self::NounONeuterHard => "N-O-N-HARD-01",
            Self::NounJoMasculineSoft => "N-JO-M-SOFT-01",
            Self::NounJoNeuterSoft => "N-JO-N-SOFT-01",
            Self::NounAHard => "N-A-HARD-01",
            Self::NounJaSoft => "N-JA-SOFT-01",
            Self::NounIFeminine => "N-I-F-01",
            Self::NounIMasculine => "N-I-M-01",
            Self::NounUMasculine => "N-U-M-01",
            Self::NounNMasculine => "N-N-M-01",
            Self::NounNNeuter => "N-N-N-01",
            Self::NounNtNeuter => "N-NT-N-01",
            Self::NounRStem => "N-R-01",
            Self::NounSNeuter => "N-S-N-01",
            Self::NounVFeminine => "N-V-F-01",
            Self::NounIndeclinable => "N-INDECL-01",
            Self::AdjectiveHardShort => "ADJ-HARD-SHORT-01",
            Self::AdjectiveHardLong => "ADJ-HARD-LONG-01",
            Self::AdjectiveSoftShort => "ADJ-SOFT-SHORT-01",
            Self::AdjectiveSoftLong => "ADJ-SOFT-LONG-01",
            Self::AdjectiveComparativeNew => "ADJ-COMP-NEW-01",
            Self::AdjectiveComparativeOld => "ADJ-COMP-OLD-01",
            Self::AdjectiveSuperlativePre => "ADJ-SUP-PRE-01",
            Self::PhraseRelativeSuperlative => "PHRASE-SUP-REL-GEN-01",
            Self::PhraseAbsoluteSuperlativeAdverb => "PHRASE-SUP-ZELO-01",
            Self::PhraseDaImperative => "PHRASE-IMPV-DA-01",
            Self::PhrasePerfect => "PHRASE-PERFECT-01",
            Self::PhrasePluperfect => "PHRASE-PLUPERFECT-01",
            Self::PhraseFutureInfinitive => "PHRASE-FUT-INF-01",
            Self::PhraseFutureParticiple => "PHRASE-FUT-PTCP-01",
            Self::PhraseFuturePerfect => "PHRASE-FUT-PERFECT-01",
            Self::PhraseConditionalOptative => "PHRASE-COND-OPT-01",
            Self::PhraseConditionalOptativeDa => "PHRASE-COND-OPT-DA-01",
            Self::PhraseConditionalOptativeElliptical => "PHRASE-COND-OPT-ELLIP-01",
            Self::PhraseConditionalOptativePassive => "PHRASE-COND-OPT-PASS-01",
            Self::PhraseAnalyticPassive => "PHRASE-PASSIVE-01",
            Self::PronounPersonalFirst => "PRON-PERS-1-01",
            Self::PronounPersonalSecond => "PRON-PERS-2-01",
            Self::PronounReflexive => "PRON-REFL-01",
            Self::PronounPersonalClitic => "PRON-PERS-CLITIC-01",
            Self::PronounAnaphoricThird => "PRON-ANAPH-3-01",
            Self::PronounAnaphoricPrepositional => "PRON-ANAPH-PREP-N-01",
            Self::PronounPronominalHard => "PRON-2P-HARD-01",
            Self::PronounPronominalSoft => "PRON-2P-SOFT-01",
            Self::PronounPronominalJ => "PRON-2P-J-01",
            Self::PronounPronominalVelar => "PRON-2P-VELAR-01",
            Self::PronounRelativeIzhe => "PRON-REL-IZHE-01",
            Self::PronounRelativePrepositional => "PRON-REL-PREP-N-01",
            Self::PronounSpecialVes => "PRON-2PSTAR-VES-01",
            Self::PronounSpecialSic => "PRON-2PSTAR-SIC-01",
            Self::PronounUniqueSi => "PRON-UNIQUE-SI-01",
            Self::PronounInterrogativeKto => "PRON-UNIQUE-KTO-01",
            Self::PronounInterrogativeChto => "PRON-UNIQUE-CHTO-01",
            Self::DeterminerInterrogativeKyi => "DET-UNIQUE-KYI-01",
            Self::VerbCopulaPresentEs => "V-COP-ES-PRES-01",
            Self::VerbCopulaFutureBud => "V-COP-BUD-PRES-01",
            Self::VerbCopulaImperfectBe => "V-COP-BE-IMPF-01",
            Self::VerbCopulaAoristBe => "V-COP-BE-AOR-01",
            Self::VerbCopulaConditionalBi => "V-COP-BI-COND-01",
            Self::VerbCopulaConditionalAoristBy => "V-COP-BY-COND-AOR-01",
            Self::VerbIA1 => "V-IA1-01",
            Self::VerbIA2 => "V-IA2-01",
            Self::VerbII1 => "V-II1-01",
            Self::VerbII2 => "V-II2-01",
            Self::VerbII3 => "V-II3-01",
            Self::VerbDictionaryMetadata => "V-LEX-META-01",
            Self::VerbInfinitive => "V-INF-01",
            Self::VerbSupine => "V-SUP-01",
            Self::VerbLParticiple => "V-LPART-01",
            Self::VerbImperfectA => "V-IMPF-A-01",
            Self::VerbImperfectYatA => "V-IMPF-YAT-A-01",
            Self::VerbImperfectPalatalizedA => "V-IMPF-PAL-A-01",
            Self::VerbImperfectContractedA => "V-IMPF-CONTRACTED-A-01",
            Self::VerbImperfectContractedYatA => "V-IMPF-CONTRACTED-YAT-A-01",
            Self::VerbImperfectContractedPalatalizedA => "V-IMPF-CONTRACTED-PAL-A-01",
            Self::VerbImperfectPresent => "V-IMPF-PRESENT-01",
            Self::VerbImperfectPresentContracted => "V-IMPF-PRESENT-CONTRACTED-01",
            Self::VerbImperfectIotated => "V-IMPF-IOTATED-01",
            Self::VerbAoristAsigmatic => "V-AOR-ASIG-01",
            Self::VerbAoristSigmaticPrimary => "V-AOR-SIG-PRIMARY-01",
            Self::VerbAoristSigmaticSecondary => "V-AOR-SIG-SECONDARY-01",
            Self::VerbAoristSigmaticVowel => "V-AOR-SIG-VOWEL-01",
            Self::VerbAoristNew => "V-AOR-NEW-01",
            Self::VerbImperative => "V-IMP-01",
            Self::VerbParticiplePresentActive => "V-PTCP-PRES-ACT-01",
            Self::VerbParticiplePresentPassive => "V-PTCP-PRES-PASS-01",
            Self::VerbParticiplePastActive => "V-PTCP-PAST-ACT-01",
            Self::VerbParticiplePastPassive => "V-PTCP-PAST-PASS-01",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RuleStep {
    pub rule_id: RuleId,
    pub before: String,
    pub after: String,
    pub reason: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PredictedForm {
    pub text: String,
    pub rule_id: RuleId,
    pub trace: Vec<RuleStep>,
}
