use std::{fs, io::Write, path::Path};

use sha2::{Digest, Sha256};

use super::*;

pub(crate) struct RegistryTables {
    pub(crate) lexemes: Table,
    pub(crate) noun_restrictions: Table,
    pub(crate) principal_parts: Table,
    pub(crate) exact_forms: Table,
    pub(crate) alignments: Table,
    pub(crate) abbreviations: Table,
    pub(crate) abbreviation_families: Table,
    pub(crate) accents: Table,
    pub(crate) accent_paradigms: Table,
    pub(crate) positional_paradigms: Table,
    pub(crate) positional_rules: Table,
    pub(crate) transformation_rules: Table,
    pub(crate) conflicts: Table,
    pub(crate) defective_inventories: Table,
    pub(crate) irregular_inventory: Table,
    pub(crate) evidence_provenance: Table,
}

pub(crate) fn emit_registry(tables: RegistryTables) -> String {
    let RegistryTables {
        mut lexemes,
        mut noun_restrictions,
        mut principal_parts,
        mut exact_forms,
        mut alignments,
        mut abbreviations,
        mut abbreviation_families,
        mut accents,
        mut accent_paradigms,
        mut positional_paradigms,
        mut positional_rules,
        mut transformation_rules,
        mut conflicts,
        mut defective_inventories,
        mut irregular_inventory,
        evidence_provenance,
    } = tables;
    lexemes.rows.sort();
    noun_restrictions.rows.sort();
    principal_parts.rows.sort();
    exact_forms.rows.sort_by(|left, right| {
        let source_rank = |source: &str| match source {
            "normative-table" => 0,
            "synodal-attestation" => 1,
            "normative-variant" => 2,
            _ => 3,
        };
        left[0]
            .cmp(&right[0])
            .then_with(|| left[1].cmp(&right[1]))
            .then_with(|| source_rank(&left[5]).cmp(&source_rank(&right[5])))
            .then_with(|| left[2].cmp(&right[2]))
            .then_with(|| left.cmp(right))
    });
    alignments.rows.sort();
    abbreviations.rows.sort();
    abbreviation_families.rows.sort();
    accents.rows.sort();
    accent_paradigms.rows.sort();
    positional_paradigms.rows.sort();
    positional_rules.rows.sort();
    transformation_rules.rows.sort();
    conflicts.rows.sort();
    defective_inventories.rows.sort();
    irregular_inventory
        .rows
        .sort_by_key(|row| row[0].parse::<u8>().ok());

    let mut output = String::from(
        "// @generated by synodal-church-slavonic-extractor; do not edit.\n\
         // Source: data/synodal/*.tsv\n\n",
    );
    emit_rows(&mut output, "LEXEMES", "RawLexeme", &lexemes.rows);
    emit_rows(
        &mut output,
        "NOUN_RESTRICTIONS",
        "RawNounRestriction",
        &noun_restrictions.rows,
    );
    emit_rows(
        &mut output,
        "PRINCIPAL_PARTS",
        "RawPrincipalPart",
        &principal_parts.rows,
    );
    emit_rows(
        &mut output,
        "EXACT_FORMS",
        "RawExactForm",
        &exact_forms.rows,
    );
    emit_rows(&mut output, "ALIGNMENTS", "RawAlignment", &alignments.rows);
    emit_rows(
        &mut output,
        "ABBREVIATIONS",
        "RawAbbreviation",
        &abbreviations.rows,
    );
    emit_rows(
        &mut output,
        "ABBREVIATION_FAMILIES",
        "RawAbbreviationFamily",
        &abbreviation_families.rows,
    );
    emit_rows(&mut output, "ACCENTS", "RawAccent", &accents.rows);
    emit_rows(
        &mut output,
        "ACCENT_PARADIGMS",
        "RawAccentParadigm",
        &accent_paradigms.rows,
    );
    output.push_str("#[allow(dead_code)]\n");
    emit_rows(
        &mut output,
        "POSITIONAL_PARADIGMS",
        "RawPositionalParadigm",
        &positional_paradigms.rows,
    );
    emit_rows(
        &mut output,
        "POSITIONAL_RULES",
        "RawPositionalRule",
        &positional_rules.rows,
    );
    emit_rows(
        &mut output,
        "TRANSFORMATION_RULES",
        "RawTransformationRule",
        &transformation_rules.rows,
    );
    emit_rows(&mut output, "CONFLICTS", "RawConflict", &conflicts.rows);
    emit_rows(
        &mut output,
        "DEFECTIVE_INVENTORIES",
        "RawDefectiveInventory",
        &defective_inventories.rows,
    );
    emit_rows(
        &mut output,
        "IRREGULAR_VERB_INVENTORY",
        "RawIrregularVerbInventory",
        &irregular_inventory.rows,
    );
    emit_rows(
        &mut output,
        "REVIEWED_EVIDENCE",
        "RawReviewedEvidence",
        &evidence_provenance.rows,
    );
    let _ = output.pop();
    output
}

pub(crate) fn emit_dictionary_registry(
    mut senses: Table,
    mut examples: Table,
    mut semantic_alignments: Table,
) -> String {
    senses.rows.sort();
    examples.rows.sort();
    semantic_alignments.rows.sort();
    let mut output = String::from(
        "// @generated by synodal-church-slavonic-extractor; do not edit.\n\
         // Source: data/synodal/senses.tsv and examples.tsv\n\n",
    );
    emit_rows(&mut output, "SENSES", "RawSense", &senses.rows);
    emit_rows(&mut output, "EXAMPLES", "RawExample", &examples.rows);
    emit_rows(
        &mut output,
        "SEMANTIC_ALIGNMENTS",
        "RawSemanticAlignment",
        &semantic_alignments.rows,
    );
    let _ = output.pop();
    output
}

pub(crate) fn emit_rows(output: &mut String, constant: &str, row_type: &str, rows: &[Vec<String>]) {
    output.push_str("pub(crate) const ");
    output.push_str(constant);
    output.push_str(": &[");
    output.push_str(row_type);
    output.push_str("] = &[\n");
    for row in rows {
        output.push_str("    ");
        output.push_str(row_type);
        output.push_str("([");
        for (index, value) in row.iter().enumerate() {
            if index > 0 {
                output.push_str(", ");
            }
            push_rust_string(output, value);
        }
        output.push_str("]),\n");
    }
    output.push_str("];\n\n");
}

pub(crate) fn push_rust_string(output: &mut String, value: &str) {
    output.push('"');
    for character in value.chars() {
        match character {
            '\\' => output.push_str("\\\\"),
            '"' => output.push_str("\\\""),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            other => output.push(other),
        }
    }
    output.push('"');
}

pub(crate) fn atomic_write(destination: &Path, bytes: &[u8]) -> Result<()> {
    let parent = destination
        .parent()
        .ok_or_else(|| ExtractionError::InvalidRow {
            file: destination.to_owned(),
            line: 0,
            reason: "destination must have a parent directory".into(),
        })?;
    fs::create_dir_all(parent)?;
    let temporary = destination.with_extension("rs.tmp");
    let mut file = fs::File::create(&temporary)?;
    file.write_all(bytes)?;
    file.sync_all()?;
    fs::rename(temporary, destination)?;
    Ok(())
}

pub(crate) fn hex_sha256(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    digest.iter().map(|byte| format!("{byte:02x}")).collect()
}
